mongo/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RecetaController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//IMPORTAR TU CONTROLADOR SI NO NO VA A FUNCIONAR

Route::get('/', function () {
    return view('welcome');
});
Route::resource('recetas',RecetaController::class);

mongo/app/Models/Receta.php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Receta extends Model
{
    protected $connection = 'mongodb';
    protected $collection = 'receta';//cambiar a la coleccion que elijan 

    //cambiar los campos
    protected $fillable = [
        'fecha','nombre_paciente','edad','peso','temperatura','dx','medicamentos','medico','cedula'
    ];
}

mongo/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

mongo/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

mongo/app/Http/Controllers/RecetaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Receta;//esto cambia 
use Illuminate\Http\Request;

class RecetaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //cambia 
        $recetas = Receta::all();
        return view('recetas.index',compact('recetas'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('recetas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

       
        
        request()->validate([
            'fecha' => 'required',
            'nombre_paciente' => 'required',
            'edad' => 'required',
            'peso' => 'required',
            'temperatura' => 'required',
            'dx' => 'required',
            'medicamentos' => 'required',
            'medico' => 'required',
            'cedula' => 'required'
        ]);
        Receta::create($request->all());
        return redirect()->route('recetas.index')
        ->with('success','receta created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Receta $receta)
    {
        return view('recetas.show',compact('receta'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Receta $receta)
    {
        return view('recetas.edit',compact('receta'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Receta $receta)
    {
        request()->validate([
            'fecha' => 'required',
            'nombre_paciente' => 'required',
            'edad' => 'required',
            'peso' => 'required',
            'temperatura' => 'required',
            'dx' => 'required',
            'medicamentos' => 'required',
            'medico' => 'required',
            'cedula' => 'required'
        ]);
        $receta->update($request->all());
        return redirect()->route('recetas.index')
                        ->with('success','receta updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Receta $receta)
    {
        $receta->delete();

        return redirect()->route('recetas.index')
                        ->with('success','receta deleted successfully');
    }
}

mongo/resources/views/recetas/create.blade.php
@extends('recetas.layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Nueva Receta</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('recetas.index') }}"> regresar</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('recetas.store') }}" method="POST">
    	@csrf
        
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>fecha:</strong>
		            <input type="text" name="fecha" class="form-control" placeholder="fecha">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>nombre_paciente:</strong>
		            <input type="text" name="nombre_paciente" class="form-control" placeholder="Nombre">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>edad:</strong>
		            <input type="text" name="edad" class="form-control" placeholder="edad">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>peso:</strong>
		            <input type="text" name="peso" class="form-control" placeholder="peso">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
		            <strong>temperatura:</strong>
		            <input type="text" name="temperatura" class="form-control" placeholder="temperatura">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
		            <strong>dx:</strong>
		            <input type="text" name="dx" class="form-control" placeholder="dx">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>medicamentos:</strong>
		            <input type="text" name="medicamentos" class="form-control" placeholder="medicamentos">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>medico:</strong>
		            <input type="text" name="medico" class="form-control" placeholder="medico">
		        </div>
		    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>cedula:</strong>
		            <input type="text" name="cedula" class="form-control" placeholder="cedula">
		        </div>
		    </div>









		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>


    </form>


@endsection

mongo/resources/views/recetas/edit.blade.php
@extends('recetas.layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Editar Receta</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('recetas.index') }}"> Back</a>
            </div>
        </div>
    </div>


    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif


    <form action="{{ route('recetas.update',$receta->id) }}" method="POST">
    	@csrf
        @method('PUT')


         <div class="row">

            <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>fecha:</strong>
                        <input type="text" name="fecha" value = "{{$receta->fecha}}" class="form-control" placeholder="fecha">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>nombre_paciente:</strong>
                        <input type="text" name="nombre_paciente" value = "{{$receta->nombre_paciente}}" class="form-control" placeholder="Nombre">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>edad:</strong>
                        <input type="text" name="edad" value = "{{$receta->edad}}" class="form-control" placeholder="edad">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>peso:</strong>
                        <input type="text" name="peso" value = "{{$receta->peso}}" class="form-control" placeholder="peso">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>temperatura:</strong>
                        <input type="text" name="temperatura" value = "{{$receta->temperatura}}" class="form-control" placeholder="temperatura">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>dx:</strong>
                        <input type="text" name="dx" value = "{{$receta->dx}}" class="form-control" placeholder="dx">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>medicamentos:</strong>
                        <input type="text" name="medicamentos" value = "{{$receta->medicamentos}}" class="form-control" placeholder="medicamentos">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>medico:</strong>
                        <input type="text" name="medico" value = "{{$receta->medico}}" class="form-control" placeholder="medico">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>cedula:</strong>
                        <input type="text" name="cedula" value = "{{$receta->cedula}}" class="form-control" placeholder="cedula">
                    </div>
                </div>
		   
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		      <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>


    </form>


@endsection

mongo/resources/views/recetas/index.blade.php
@extends('recetas.layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Recetas</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('recetas.create') }}"> Crear Receta</a>
            </div>
        </div>
    </div>


    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered">
        <tr>
            
            <th>fecha</th>
            <th>nombre_paciente</th>
            <th>edad</th>
            <th>peso</th>
            <th>temperatura</th>
            <th>dx</th>
            <th>medicamentos</th>
            <th>medico</th>
            <th>cedula</th>
            <th width="280px">Action</th>
        </tr>
	    @foreach ($recetas as $receta)
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $receta->fecha }}</td>
	        <td>{{ $receta->nombre_paciente }}</td>
            <td>{{ $receta->edad }}</td>
            <td>{{ $receta->peso }}</td>
            <td>{{ $receta->temperatura }}</td>
            <td>{{ $receta->dx }}</td>
            <td>{{ $receta->medicamentos }}</td>
            <td>{{ $receta->medico }}</td>
            <td>{{ $receta->cedula }}</td>
	        <td>
                <form action="{{ route('recetas.destroy',$receta->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('recetas.show',$receta->id) }}">Show</a>
                    <a class="btn btn-primary" href="{{ route('recetas.edit',$receta->id) }}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
	        </td>
	    </tr>
	    @endforeach
    </table>


@endsection

mongo/resources/views/recetas/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laravel 5.6 CRUD Application</title>
	<link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css" rel="stylesheet">
</head>
<body>


<div class="container">
    @yield('content')
</div>


</body>
</html>

mongo/resources/views/recetas/show.blade.php
@extends('recetas.layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Book</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('recetas.index') }}"> Back</a>
            </div>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>fecha:</strong>
                {{ $receta->fecha }}

            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>nombre_paciente:</strong>
                {{ $receta->nombre_paciente }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>edad:</strong>
                {{ $receta->edad }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>peso:</strong>
                {{ $receta->peso }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>temperatura:</strong>
                {{ $receta->temperatura }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>dx:</strong>
                {{ $receta->dx }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">

                <strong>medicamentos:</strong>
                {{ $receta->medicamentos }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">


                <strong>cedula:</strong>
                {{ $receta->cedula }}
            </div>
        </div>
    </div>
@endsection